new update with UI and Instructions

diff --git a/fig b/fig
--- a/fig
+++ b/fig
@@ -1,66 +1,18 @@
 #!/usr/bin/env bash
 # Author: Hakxcore https://github.com/hakxcore
 
-
 #sudo apt install html-xml-utils
 #sudo apt  install libxml2-utils
-
-
-#
-#cat file2 | grep -i -B 120 'Shortcuts' | pv -qL 50
-
-
-
 
 currentVersion="v0.0.1"
 configuredClient=""
 
-
-# Parameters
-# Parameter Description
-# version (optional)
-  
-# Model version. Valid values: 1, 2, 3
-# confidence (optional)
-  
-# Valid values: 0.0 - 1.0 Since all of our faces are generated by AI, we’ve used several neural networks to classify images. This parameter controls the threshold of how confident were predictions. Default: 0.5
-# emotion (optional)
-  
-# Valid values: joy, neutral, surprise
-# gender (optional)
-  
-# Valid values: male, female
-# age (optional)
-  
-# Valid values: infant, child, young-adult, adult, elderly
-# ethnicity (optional)
-  
-# Valid values: white, latino, asian, black
-# eye_color (optional)
-  
-# Valid values: brown, blue, gray, green
-# hair_color (optional)
-  
-# Valid values: brown, blond, black, gray, red
-# hair_length (optional)
-  
-# Valid values: short, medium, long
-# order_by (optional)
-  
-# Valid values: latest, oldest, random, Default: latest.
-# page (optional)
-#   Page number to retrieve, Default: 1
-# per_page (optional)
-  
-# Number of items per page. Maximum: 100, Default: 10
-
-
 #colors
-RED="$(printf '\033[31m')" GREEN="$(printf '\033[32m')" ORANGE="$(printf '\033[33m')" BLUE="$(printf '\033[34m')"
+RED="$(printf '\033[31m')" GREEN="$(printf '\033[1;32m')" ORANGE="$(printf '\033[33m')" BLUE="$(printf '\033[34m')"
 MAGENTA="$(printf '\033[35m')" CYAN="$(printf '\033[36m')" WHITE="$(printf '\033[37m')" BLACK="$(printf '\033[30m')" 
 REDBG="$(printf '\033[41m')" GREENBG="$(printf '\033[42m')" ORANGEBG="$(printf '\033[43m')" BLUEBG="$(printf '\033[44m')", 
 MAGENTABG="$(printf '\033[45m')" CYANBG="$(printf '\033[46m')" WHITEBG="$(printf '\033[47m')" BLACKBG="$(printf '\033[40m')"
-RESETBG="$(printf '\e[0m')" BLINK="$(printf '\033[5;31m')"
+RESETBG="$(printf '\e[0m')" BLINK="$(printf '\033[5;31m')" YELLOW="$(printf '\033[1;33m')"
 
 ##Platform Check
 if [[ "$OSTYPE" == linux-android* ]]; then
@@ -170,28 +122,81 @@ checkInternet()
   curl -s github.com > /dev/null 2>&1 || { echo "Error: no active internet connection" >&2; return 1; } # query github with a get request
 }
 
+banner()
+{
 
+echo -e "\t\t\t\t$GREEN·▄▄▄▪   ▄▄ • "
+echo -e "\t\t\t\t▐▄▄·██ ▐█ ▀ ▪ "
+echo -e "\t\t\t\t██▪ ▐█·▄█ ▀█▄ "
+echo -e "\t\t\t\t██▌.▐█▌▐█▄▪▐█ "
+echo -e "\t\t\t\t▀▀▀ ▀▀▀·▀▀▀▀ $RESETBG$BLUE$currentVersion$RESETBG"
+echo ""
+echo -e "$YELLOW\t\t\t ------(Instructions)------$RESETBG"
+echo -e "$MAGENTA\t\t -\U2192 Confidence$CYAN: 0.0 - 1.0, Default: 0.5"   
+sleep 1
+echo -e "$MAGENTA\t\t -\U2192 Emotion$CYAN:    joy, neutral, surprise"
+sleep 1
+echo -e "$MAGENTA\t\t -\U2192 Gender$CYAN:     male, female"
+sleep 1
+echo -e "$MAGENTA\t\t -\U2192 Age$CYAN:        infant, child, young-adult, adult, elderly"
+sleep 1
+echo -e "$MAGENTA\t\t -\U2192 Ethnicity$CYAN:  white, latino, asian, black"
+sleep 1
+echo -e "$MAGENTA\t\t -\U2192 Eye_color$CYAN:  brown, blue, gray, green"
+sleep 1
+echo -e "$MAGENTA\t\t -\U2192 Hair_color$CYAN: brown, blond, black, gray, red"
+sleep 1
+echo -e "$MAGENTA\t\t -\U2192 Hair_length$CYAN:short, medium, long"
+sleep 1
+echo -e "$MAGENTA\t\t -\U2192 Order_by$CYAN:   latest, oldest, random, Default: latest. "
+sleep 1
+# echo -e "$MAGENTA 10. page"
+# echo -e "$CYAN\tPage number to retrieve, Default: 1"
+# sleep 1
+# echo "$MAGENTA 11. per_page"
+# echo -e "$CYAN\tNumber of items per page. Maximum: 100, Default: 10"
+# sleep 1
+}
 ##Main function
-Main(){
+getFakeId()
+{
+  banner
   getConfiguredW3m
   getConfiguredPv
-  checkInternet
   echo $BLUE"--------------------------------------------------"$GREEN"Images Size Wise$BLUE--------------------------------------------------------"
-  curl -s --header "Authorization: API-Key NS6_7xnlFmzIiOu5Eeg9vw" "https://api.generated.photos/api/v1/faces?per_page=1&gender=$1&emotion=neutral&age=$2" | jq | grep https | awk {'print "Image Size "$1,$2'} | sed 's/"//g' | nl
+  curl --header "Authorization: API-Key NS6_7xnlFmzIiOu5Eeg9vw" https://api.generated.photos/api/v1/faces?per_page=1&gender=$1&emotion=neutral&age=$2 | jq | grep https | awk {'print "Image Size "$1,$2'} | sed 's/"//g' | nl
+  sleep 3
   echo -e $BLUE"\n--------------------------------------------------"$GREEN"Fake ID Data$BLUE--------------------------------------------------------"
-  
-  w3m -dump https://www.fakenamegenerator.com/gen-random-us-it.php | grep -i -B 120 'Shortcuts' | html2text | pv -qL 50
+  if [[ "$1" == "male" && "$2" == "child" ]]; then
+  	gen="97"
+  	min-age="2"
+  	max-age="17"
+  elif [[ "$1" == "male" && "$2" == "adult" ]]; then
+  	gen="97"
+  	min-age="18"
+  	max-age="24"
+  elif [[ "$1" == "male" && "$2" == "young-adult" ]]; then
+  	gen="97"
+  	min-age="25"
+  	max-age="30"
+  elif [[ "$1" == "male" && "$2" == "elderly" ]]; then
+  	gen="97"
+  	min-age="31"
+  	max-age="60"
+  fi
+  #https://www.fakenamegenerator.com/gen-random-us-it.php | grep -i -B 120 'Shortcuts' | pv -qL 50
+  w3m -dump https://www.fakenamegenerator.com/advanced.php?t=country&n%5B%5D=us&c%5B%5D=us&gen=$gen&age-min=$min-age&age-max=$max-age
 }
 
 ##Usage and Help
 usage()
 {
   cat <<EOF
-facegen <age>
+fig <age>
 age=infant, child, young-adult, adult, elderly
 Description: Genrate images of the peoples that doesn't even exists in this world.
 
-Usage: facegen age
+Usage: fig age
   -u  Update Tool
   -h  Show the help
   -v  Get the tool version
@@ -203,11 +208,18 @@ EOF
 }
 
 ##Options(flags)
-while getopts "e:d:uvh" opt; do
+while getopts "s:a:uvh" opt; do
   case "$opt" in
     \?) echo "Invalid option: -$OPTARG" >&2
         exit 1
         ;;
+    s)
+		if [[ "$(echo "$@" | grep -Eo "\-s")" == "-s" ]];then gender="true";fi
+		;;
+	a)
+		if [[ "$(echo "$@" | grep -Eo "\-a")" == "-a" ]];then age="true";fi
+		;;
+
     h)  usage
         exit 0
         ;;
@@ -238,10 +250,22 @@ elif [[ $# == "1" ]]; then
     usage
     exit 0
   fi
-  else
-        #clear; echo "You shouldnt be here but maaaaaaybeee you slipped passed me, learn to use the tool!"; sleep 5; clear;
-  #usage
-  Main $1 $2
-  exit 1
 fi
 
+
+if ($age && ! $gender)  || ($gender && ! $age);then
+  echo "Error: the -a and the -s flag must be used to fetch lyrics."
+  exit 1
+elif $age && $gender;then
+  gender=$(echo "$@" | grep -Eo "\-s [ a-z A-Z 0-9 . \ ]*[ -]?" | sed s/-s//g | sed s/-//g | sed s/^" "//g)
+  if [[ $gender == "" ]];then { echo "Error: gender could not be parsed from input."; exit 1; };fi
+  age=$(echo "$@" | grep -Eo "\-a [ a-z A-Z 0-9 . \ ]*[ -]?" | sed s/-a//g | sed s/-//g | sed s/^" "//g)
+  if [[ $age == "" ]];then { echo "Error: age could not be parsed from input."; exit 1; };fi
+  getConfiguredClient || exit 1
+  checkInternet || exit 1
+  getFakeId "$gender" "$age" || exit 1
+else
+  { clear; echo "You shouldnt be here but maaaaaaybeee you slipped passed me, learn to use the tool!"; sleep 5; clear;}
+  usage
+  exit 1
+fi
